name: 'gaming_pipeline'
version: '1.0.0'
config-version: 2
 
profile: 'gaming_pipeline'
 
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]
 
models:
  gaming_pipeline:
    staging:
      +schema: STAGING
      +materialized: view
    mart:
      +schema: MART
      +materialized: table